<?php

namespace Your\WebApp\Leaves\Posts;


use Rhubarb\Leaf\Crud\Leaves\CrudLeaf;

class PostsItem extends CrudLeaf
{

    /**
     * Returns the name of the standard view used for this leaf.
     *
     * @return string
     */
    protected function getViewClass()
    {
        return PostsItemView::class;
    }

    protected function redirectAfterSave()
    {
        parent::redirectAfterSave(); // TODO: Change the autogenerated stub
    }

    protected function redirectAfterCancel()
    {
        parent::redirectAfterCancel(); // TODO: Change the autogenerated stub
    }


}